version: '3.8'

services:
  php:
    build: .
    container_name: symfony_php
    volumes:
      - .:/var/www
    ports:
      - "8000:8000"
    environment:
      - APP_ENV=dev
      - API_TOKEN=${API_TOKEN}
    depends_on:
      - db

  db:
    image: mysql:latest   
    container_name: symfony_db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: symfony_db
    ports:
      - "3306:3306"
